Feature(#133): 로그인 화면 UI
boostcampwm2023/and01-SnapPoint pull request #144
Opened 2023-11-27 14:50 UTC by rbybound

## 작업 개요

- [x] 임시 UI 생성
- [x] 입력 양식 확인

## 작업 사항

- 이메일과 비밀번호만 입력 받는 화면을 임시로 만들었습니다.
- 아이디(이메일)가 이메일 형식인지 확인하고, 비밀번호는 6자리 이상이면 로그인 버튼이 활성화됩니다.

## 고민한 점들(필수 X)

## 스크린샷(필수 X)

- 로그인 화면의 임시 UI
![Screenshot_20231127_234839](https://github.com/boostcampwm2023/and01-SnapPoint/assets/76683420/d8ea81c0-0d82-4cda-8eec-128a476f92be)

2023-11-27 15:01 UTC, wsb7788 requested changes
editText에 대한 부분은 material3에서 제공하는 위젯을 참고해서 만들면 좋을 것 같아요.

2023-11-27 15:25 UTC, rbybound commented on android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginResult.kt
> +data class LoginResult(
sealed class를 써야 한다면 이름을 Event로 해서 다른 UI랑 맞추는 게 좋을 것 같네요

2023-11-28 06:23 UTC, rbybound commented on android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginViewModel.kt
> +    private fun isPasswordValid(password: String): Boolean {
다른 사이트를 보니까 이메일은 이메일 형식을 확인하고, 비밀번호는 비어있지만 않으면 요청을 보내는 것 같아서 비슷하게 했어요. (네이버/카카오/구글)

2023-11-28 06:29 UTC, LJG7123 commented on android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginViewModel.kt
> +    fun updateUsername(username: String) {
username보다는 email이 더 적합한 이름일 것 같아요!

2023-11-28 06:29 UTC, LJG7123 approved these changes
고생하셨습니다!!

2023-11-28 06:30 UTC, wsb7788 approved these changes
고생하셨습니다 !

2023-11-28 06:30 UTC, wsb7788 commented on android/app/src/main/java/com/boostcampwm2023/snappoint/presentation/login/LoginViewModel.kt
> +    private val _uiState: MutableStateFlow<LoginFormState> = MutableStateFlow(LoginFormState())
LoginFormUiState로 변경하면 좋을 것 같습니당

2023-11-28 06:35 UTC, merged